### ISSUE TITLE
Error running in Ubuntu 22.04.

### ISSUE THREAD

**Issue by slannon97** [gumerov-amir/TTMediaBot#106]
I'm trying to run the bot after performing a clean install of Ubuntu 22.04 LTS. I followed all the steps and installed all necessary requirements, but I receive the following error.
" /home/chris/.local/lib/python3.10/site-packages/pydantic/_migration.py:283: User
 Warning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:V
 alidationError`.                                                                
   warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')         
 Traceback (most recent call last):                                              
   File "/home/chris/TTMediaBot/TTMediaBot.py", line 7, in <module>              
     from bot import Bot, app_vars                                               
   File "/home/chris/TTMediaBot/bot/__init__.py", line 10, in <module>           
     from bot import (                                                           
   File "/home/chris/TTMediaBot/bot/TeamTalk/__init__.py", line 19, in <module>  
     from bot.TeamTalk.thread import TeamTalkThread                              
   File "/home/chris/TTMediaBot/bot/TeamTalk/thread.py", line 14, in <module>    
     from bot.TeamTalk.structs import *                                          
   File "/home/chris/TTMediaBot/bot/TeamTalk/structs.py", line 3, in <module>    
     import TeamTalkPy                                                           
   File "/home/chris/TTMediaBot/TeamTalkPy/__init__.py", line 1, in <module>     
     from .TeamTalk5 import *                                                    
   File "/home/chris/TTMediaBot/TeamTalkPy/TeamTalk5.py", line 24, in <module>   
     dll = cdll.LoadLibrary("libTeamTalk5.so")                                   
   File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary       
     return self._dlltype(name)                                                  
   File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__          
     self._handle = _dlopen(self._name, mode)                                    
 OSError: libssl.so.1.1: cannot open shared object file: No such file or director
 y                                                                               "
Is this perhaps an error with the TT SDK? When I installed the bot on Ubuntu 20.04, I noticedi t was using 5.8, which may not be compatible with 22.04. I'm at a loss and not sure what to do to fix this.

**Comment by johanntan** [comment]
You will need to install the libssl package.
```
wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2_amd64.deb'
sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2_amd64.deb
```

**Comment by beqabeqa473** [comment]
You should upgrade a tt-sdk, but in this case, you will need to make
some changes in TtMediaBot itself to make it work correctly.

On 12/25/23, Christopher Wright ***@***.***> wrote:
> I receive the following error.
> " dpkg: dependency problems prevent configuration of libssl-dev:amd64:
>
>   libssl-dev:amd64 depends on libssl1.1 (= 1.1.1f-1ubuntu2); however:
>
>    Package libssl1.1 is not installed.
>
>
>  dpkg: error processing package libssl-dev:amd64 (--install):
>
>   dependency problems - leaving unconfigured
>
>  Errors were encountered while processing:
>
>   libssl-dev:amd64"
> I tried running sudo apt install libssl-dev, but this doesn't work either.
> Does this involve downgrading a component? If so, I'd rather not do that.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/gumerov-amir/TTMediaBot/issues/106#issuecomment-1868855124
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by lbk2907** [comment]
Try this.

echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee
/etc/apt/sources.list.d/focal-security.list && apt update && apt install
libssl1.1

**Comment by slannon97** [comment]
Thank you, this fixed the issue. I don't like it's a workaround. The program should be updated at some point rather than relying on old outdated components that don't ship with newer distros.

**Comment by musti12kelek** [comment]
Hello, although I wrote the commands you specified, I could not run TTMediaBot in Ubuntu 22.04. I didn't know what I should do.
