### ISSUE TITLE
libssl dependencies

### ISSUE THREAD

**Issue by rut-04** [gumerov-amir/TTMediaBot#112]
I have tried set up a TTBot lately. Tried on ubuntu and debian and ever i have this answer:

/home/bot/.local/lib/python3.10/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:Validati
onError` has been moved to `pydantic:ValidationError`.                                                                  
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')                                                 
Traceback (most recent call last):                                                                                      
  File "/home/bot/TTMediaBot/TTMediaBot.py", line 7, in <module>                                                        
    from bot import Bot, app_vars                                                                                       
  File "/home/bot/TTMediaBot/bot/__init__.py", line 10, in <module>                                                     
    from bot import (                                                                                                   
  File "/home/bot/TTMediaBot/bot/TeamTalk/__init__.py", line 19, in <module>                                            
    from bot.TeamTalk.thread import TeamTalkThread                                                                      
  File "/home/bot/TTMediaBot/bot/TeamTalk/thread.py", line 14, in <module>                                              
    from bot.TeamTalk.structs import *                                                                                  
  File "/home/bot/TTMediaBot/bot/TeamTalk/structs.py", line 3, in <module>                                              
    import TeamTalkPy                                                                                                   
  File "/home/bot/TTMediaBot/TeamTalkPy/__init__.py", line 1, in <module>                                               
    from .TeamTalk5 import *                                                                                            
  File "/home/bot/TTMediaBot/TeamTalkPy/TeamTalk5.py", line 24, in <module>                                             
    dll = cdll.LoadLibrary("libTeamTalk5.so")                                                                           
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary                                               
    return self._dlltype(name)                                                                                          
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__                                                  
    self._handle = _dlopen(self._name, mode)                                                                            
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by cyrmax** [comment]
What version of TeamTalk sdk do you use? From what commit you are starting the bot?
It is known that new TT sdk does not run correctly on Debian 11 and before and probably on Ubuntu 18 or 20 or before.

**Comment by lbk2907** [comment]
Eps, It doesn't run on Ubuntu 20.
