### ISSUE TITLE
a bug when the bot enter ina tt5Srv in ubuntu:

### ISSUE THREAD

**Issue by sanagui-dj** [gumerov-amir/TTMediaBot#66]
hy guys. how are you? well, i'm trying to use this bot and i can't. i follow the `instructions` as here in gitup, but i can't get the correct funcion of the bot. how can i do it?

INFO [2022-04-08 01:28:40,566]: Started in MainThread file: __init__.py line 89 function run
INFO [2022-04-08 01:28:55,621]: New message h from sanagui in MainThread file: __init__.py line 94 function run
ERROR [2022-04-08 01:28:55,623]:  in Thread-4 file: __init__.py line 110 function _run
Traceback (most recent call last):
  File "/home/music/TTMediaBot/bot/commands/__init__.py", line 95, in _run
    self.ttclient.send_message(
  File "/home/music/TTMediaBot/bot/TeamTalk/__init__.py", line 156, in send_message
    message = TeamTalkPy.TextMessage()
  File "/home/music/TTMediaBot/TeamTalkPy/TeamTalk5.py", line 727, in __init__
    assert(DBG_SIZEOF(TTType.TEXTMESSAGE) == ctypes.sizeof(TextMessage))
AssertionError

**Comment by lbk2907** [comment]
Hey there. Are you using the latest TeamTalkSDK? If yes, you need to
downgrade to version 5.8.1 (at least). You can find the TeamTalkSDK from
the below link. Download the version 5.8B. Thanks.

https://bearware.dk/teamtalksdk

**Comment by cyrmax** [comment]
@sanagui-dj Hello.
Are you still experiencing this problem? As @lbk2907 noticed, you should use TeamTalk sdk version 5.8. 
If you use TeamTalk sdk 5.8 and latest version of TTMediaBot and issue still persists please reopen this issue or create new one with complete logs and exact versions of all components you use.
